### PR TITLE
Possible fix for upper case and the to small table

### PR DESCRIPTION
**Pull request by Endor8**
I made some changes to the app.css file, so it looks correctly for German locale.
The too small Table for the language chose for OCR language I tried also to fix 
it. I also reduced a little bit the font size , from 40 to 20px, but this is just my
idea, you can leave also your 40px.  What you think about this?
Cheers
Endor

### CODE REVIEW

**Comment by Noitidart** [comment]
Thank you so much sir for this PR! I can clearly see the things you changed.

I honestly preferred the all caps. The ui guy/stylist I worked with to create this style preferred the all caps too and I paid him $15 to work with me haha; so I was hesitant to move away from the caps. But if people think this is better then I am all for it.

I really like that too narrow fix for the dropdown. I tried some stuff but I was breaking things. I'll experiement with your solution.

**Comment by Endor8** [comment]
Ok. Thank you. You made a great work.
Cheers
Endor

**Comment by Endor8** [comment]
There is another possible solution, you can make the css on language depending.
For example: 
If you at this to the file i proposed:
/*Language-specific*/
:lang(en){text-transform: uppercase;}

in English locale every thing got displayed in upper case, all other languages
in the default stile.
Cheers
Endor

**Comment by Endor8** [comment]
You can make it also so, 
with this lines in your original App.css only the German locale changes:

/*Language-specific*/
:lang(de){text-transform: none;}
:lang(de).pref-block-title h4 {text-transform: none;}
:lang(de) #filters button{text-transform: none;}
:lang(de) .slip-overlay h4 {text-transform: none;}
:lang(de) .slip-overlay h5 {text-transform: none;}
:lang(de) .slip-overlay a  {text-transform: none;}

all gets showed as is should in German locale, without influence of
other locales. I Think this could be a better way. 
Cheers
Endor

**Comment by Noitidart** [comment]
Ah these are good ideas. Does the capitalization make it unreadable in German?

**Comment by Endor8** [comment]
Hi. The complete capitalization is unusual in German locale, so it look 
I have updated the lines, now also the issue with the to small table
for OCR language chose is fixed only for German locale:

/*  Language-specific  */
:lang(de){text-transform: none;}
:lang(de).pref-block ul li{text-transform: none;}
:lang(de).b-md{text-transform: none;}
:lang(de).pref-block-title h4 {text-transform: none;}
:lang(de) #filters button{text-transform: none;}
:lang(de) .slip-overlay h4 {text-transform: none;}
:lang(de) .slip-overlay h5 {text-transform: none;}
:lang(de) .slip-overlay a {text-transform: none;}
:lang(de) .dropdown-list-item {min-width: 140%;} 
:lang(de) .dropdown-display{min-width: 140%;} 

I hope this can help you.
Cheers
Endor

**Comment by Noitidart** [comment]
It helps a lot thank you! I have contacted the UI guy again to see if he can come up with some nice disign that works for all locales.

**Comment by Noitidart** [comment]
Hey @Endor8 I merged this and modified it a bit. Please try out this xpi it should work well. The drop down still overflows, that change was affecting the size of the pref boxes. So we'll have to address that in another way. The guy I bought this template from I asked him to come up with something.

This attachement should have no text transform if German. We should ask all the other lang coodrindators to see if they want their language lower cased as well.

[nativeshot-v1.12b.rev19.zip](https://github.com/Noitidart/NativeShot/files/485093/nativeshot-v1.12b.rev19.zip)

**Comment by Endor8** [comment]
Hi.
It looks nice. Very good.
Yes, the Table still overflows.
But anything else look great.
Thank you very much.
Yes you should ask all the other lang coodrindators to see if they want
their language lower cased as well.
Cheers
Endor

**Comment by Noitidart** [comment]
Hello my dear translators @noureddin, @AdmiralAnimE, @TheRabbitter, @yfdyh000, @goldie-lin, @MarkH, @TonnesM, @mdr-ksk, @tojazmin, @Endor8, @AlessandroMenti, @marsf, @zygimantus, @gymka, @teo951, @Ricardo-Simoes, @Jobava, @insolor, @veadarkin, @AlejandroPerezMartin, @MarceloGhelman - does your language need the no "text-transfrom" to upper case as seen above?

**Comment by AdmiralAnimE** [comment]
Yes please, upper case is hard to read. I'd like if you make another change to the css:
How it looks now:
https://i.imgur.com/ihARg0t.png
How it looks after my small change:
https://i.imgur.com/G9NL5Li.png
What I changed:
.slip-overlay a{
padding: 0.5em;
text-transform: uppercase <--- removed
}

**Comment by insolor** [comment]
I haven't try, but from what I see in @AdmiralAnimE screenshots, I think Russian doesn't need text-transform too.

**Comment by Noitidart** [comment]
Thank you @AdmiralAnimE and @insolor ! :)  I updated with your recommended changes please try out this xpi:

[nativeshot-v1.12b.rev20.zip](https://github.com/Noitidart/NativeShot/files/485566/nativeshot-v1.12b.rev20.zip)

**Comment by AdmiralAnimE** [comment]
Thanks but please reduce padding on the buttons, they are overflowing.

**Comment by Noitidart** [comment]
Oops forgot that, will right away

**Comment by Noitidart** [comment]
@AdmiralAnimE I changed the padding but its still overflowing for twitter:



Is it possible to shorten them? Or is that the shortest it can get? No problem either way. It's usable. We're just trying to make it pretty now. :)

**Comment by AdmiralAnimE** [comment]
Yes I just changed it :)

**Comment by Noitidart** [comment]
@AdmiralAnimE yay thank you! I'll update and see if the padding needs update.

**Comment by AdmiralAnimE** [comment]
@Noitidart  👍 Thank you!

**Comment by AlessandroMenti** [comment]
For Italian, text-transform is not needed (complete capitalization can be kept).

**Comment by Noitidart** [comment]
Awesome thanks @AlessandroMenti!

**Comment by TheRabbitter** [comment]
Catalan does not need text-transform either.

**Comment by Noitidart** [comment]
Very cool gràcies @TheRabitter!

**Comment by TonnesM** [comment]
My locale doesn’t "need" text-transform, and frankly I don’t think any locale does.

AFAICT the feature is only a nice-to-have because it’s technically possible (and not hard to implement), but it ignores grammar rules and therefor messes up any localization. If capitalization is required somewhere, it should be included in the source string when appropriate. It’s not nice to "dress up" text strings either automatically or manually and may lead to less readability and a bad impression to users.

**Comment by Noitidart** [comment]
Thanks @TonnesM for sharing that. The text-transfrom to all upper case came with the design I purchased.

That's a good point on to make it be upper or not upper in the locale files. Then I can use the string `blah_upper` or `blah_normal` in places. I did it extensively so it's hard to change right now. But if the auto-uppercase makes a language not understandable I can do a quick patch to not have any transform to auto-uppercase for that whole lang.

**Comment by noureddin** [comment]
Arabic letters don't have cases, so it's doesn't matter. The same applies to Persian, Urdu, and some other languages.

**Comment by Noitidart** [comment]
Very interesting thanks for sharing! That is very cool about those languages. No casing means no need for the shift key! haha

**Comment by Endor8** [comment]
Hi.
Have you found a way for the overflowing Table?

I changed this code, now it should only working on that Table:

@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document url("about:nativeshot?options"),
               url("about:nativeshot")
 {
:lang(de) .pref-block-btns .dropdown-list-item {min-width: 140%
!important;}
:lang(de) .pref-block-btns .dropdown-display{min-width: 140% !important;}

}

I don't know if this could help you.
Cheers
Endor

**Comment by Noitidart** [comment]
Thanks @Endor8, I haven't found a solution yet that works elegantly. But yours is nice it only affects that. What I am trying to do is center the text, I right now have a weird padding thing going on there. Your code there will definitely help me! :) But I am trying to make it so its not language dependent because all languages have the same problem.

**Comment by noureddin** [comment]
> Very interesting thanks for sharing! That is very cool about those languages. No casing means no need for the shift key! haha
@Noitidart, Yes. In fact, in Arabic, we use the shift key for few letters (3 to 6, depending on the typer), the vowel marks (usually not written), and some punctuation marks. :)

**Pull request merged**
