### PR TITLE
Romanian localization for NativeShot

### PR DESCRIPTION
**Pull request by Jobava**
I added a quick Romanian language localization. Check back with me if there are any issues with it. I will also be following this project.

Jobava

### CODE REVIEW

**Comment by Jobava** [comment]
This is a diff view english-romanian in case you need one:

https://github.com/Jobava/L10n-mozilla-addon-NativeShot/commit/876c2eb92dc9093848808f49ab5131d5dfcf67d0

**Comment by Noitidart** [comment]
Thank you so much @Jobava ! :)

**Comment by Noitidart** [comment]
Hi there @Jobava could you please submit translation for Romanian for Chrome Store Foxified on Babelzilla if you have some time - https://github.com/Noitidart/Chrome-Store-Foxified/issues/34

**Comment by Noitidart** [comment]
I merged in the new stuff from babelzilla and gave credit for it :) in forgot to close this.

**Pull request closed without merging**
