### PR TITLE
Added Spanish translation

### PR DESCRIPTION
**Pull request by AlejandroPerezMartin**
Hi @Noitidart, here is the Spanish translation 😄

### CODE REVIEW

**Comment by Noitidart** [comment]
Superb! Thank you! Merged!

**Comment by Noitidart** [comment]
Also uploaded to Babelzilla so es-ES is at 100% thank you!

**Comment by Noitidart** [comment]
Hey there @AlejandroPerezMartin if you have some time may you please translate 3 remaining strings :) No rush, only if you have time - http://beta.babelzilla.org/projects/p/nativeshot/language/es-ES/

**Comment by Noitidart** [comment]
Awesome! Thank you so much for the fast update @AlejandroPerezMartin ! :)

**Comment by AlejandroPerezMartin** [comment]
You're welcome @Noitidart!

**Pull request merged**
