### PR TITLE
patch removes my fixes

### PR DESCRIPTION
**Pull request by gymka**
after initial translation i fixed translation, your patch removed my fixes. made good patch

### CODE REVIEW

**Comment by Noitidart** [comment]
Ooo, thanks for this catch! I had pulled from babelzilla to here. I'll make sure to push from here to babelzilla for this. :)

**Comment by Noitidart** [comment]
Pushed from GH to BZ. This was the results:
```
Lithuanian (lt)
main.dtd: 0 updated, 1 added
main.properties: 0 updated, 9 added
```

**Comment by gymka** [comment]
i'll update only version in github, i'm coordinator in babelzilla, so all changes will come only with my approval... keep github version up to date and all will be ook:D

**Comment by Noitidart** [comment]
Understood, thank you friend!

**Comment by gymka** [comment]
but in end of day... someone likes github, someone babelzilla. so one person will work there, other here... if you always pull from one source it's not the fact that you'll get latest translation:)
2016-09-14 19:06, Noitidart rašė:

**Comment by Noitidart** [comment]
Very true. I can't boss anyone around they are putting in their free time for Firefox and my project, whatever they are happy with.

I should become more diligent and as I merge it onto github i should push to babelzilla right away. That way I won't make mistake. I'll start this from now on.

**Pull request merged**
