### PR TITLE
lithuanian language

### PR DESCRIPTION
**Pull request by gymka**

### CODE REVIEW

**Comment by gymka** [comment]
translated only 1 string, it's just to create folder:)

**Comment by gymka** [comment]
Initial translation, only "on paper":) need review in live addon.

**Comment by Noitidart** [comment]
Super! Thank you! Should I merge this in now?

**Comment by gymka** [comment]
You can merge, who knows when i'll test:) maybe today maybe after week..

**Comment by Noitidart** [comment]
Thank you @gymka! Merged :) I'll upload this to babelzilla later tonight please

**Comment by Noitidart** [comment]
Merged onto babelzilla - lt at 100%

**Pull request merged**
